services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ["npm", "run", "dev"]
  proxy:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf
